apiVersion: v1
kind: Service
metadata:
  name: {{ include "zinc.fullname" . }}
  labels:
    {{- include "zinc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30000
      name: http
  selector:
    {{- include "zinc.selectorLabels" . | nindent 4 }}
