apiVersion: v1
kind: Service
metadata:
  name: {{ include "zinc.fullname" . }}-headless
  labels:
    {{- include "zinc.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zinc.selectorLabels" . | nindent 4 }}
