apiVersion: v1
kind: Service
metadata:
  name: z
  namespace: zinc
spec:
  #clusterIP: None
  type: NodePort
  selector:
    app: zinc
  ports:
  - name: http
    port: 4080
    targetPort: 4080
    nodePort: 30000

---

# create statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zinc
  namespace: zinc
  labels:
    name: zinc
spec:
  serviceName: z
  replicas: 1
  selector:
    matchLabels:
      name: zinc
      app: zinc
  template:
    metadata:
      labels:
        name: zinc
        app: zinc
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      # terminationGracePeriodSeconds: 0
      containers:
        - name: zinc
          image: public.ecr.aws/zinclabs/zinc:latest
          env:
            - name: ZINC_FIRST_ADMIN_USER
              value: admin
            - name: ZINC_FIRST_ADMIN_PASSWORD
              value: Complexpass#123
            - name: ZINC_DATA_PATH
              value: /go/bin/data
          # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1024m
              memory: 2048Mi
            requests:
              cpu: 32m
              memory: 50Mi
          ports:
            - containerPort: 4080
              name: http
          volumeMounts:
          - name: data
            mountPath: /go/bin/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      # storageClassName: default
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 10Gi

